apiVersion: v1
kind: ConfigMap
metadata:
  name: xiu-node-configmap
  namespace: xiu-prod-namespace
  labels:
    app: xiu
    environment: prod
data:
  config_rtmp.toml: |
    [rtmp]
    enabled = true
    port = 1935

    [hls]
    enabled = true
    port = 8080
   
    [httpflv]
    enabled = true
    port = 8081
   
    [log]
    level = "info"